### ISSUE TITLE
OSPy, OSPi, Sip, HVAC

### ISSUE THREAD

**Issue by martinpihrt** [bkoblenz/HVAC#2]
Hi,
it is possible to connect in some way?
Thank you in advance
admin@pihrt.com

**Comment by bkoblenz** [comment]
What did you have in mind?

**Comment by martinpihrt** [comment]
I would like to contact you for help in my OSPy wateringer branch by Rimco (original OSPi Dan-in ca branch). I found that you have your version of HVAC and understand Python programming. I don't know anyone around me who can help me with this.
What's going on:
Since 2013, I have been using the original version of OSPi on which I have built a watering can. Subsequently, Rimco refactor the OSPi version and an OSPy version was created. I started using the OSPy version and contributed to this branch (plugins, etc.). Author Rimco stopped responding to my call, so I continued to develop my OSPy branch with lots of other improvements.
The whole OSPy is now complete in 3 languages ​​and has a lot of extensions. https://github.com/martinpihrt/OSPy

I would need from you if you are willing to help with 2 tasks for which I am not enough.
a) I made a section for users, where you can add other users (name, password and access rights).
I don't know, but how to make the given users only possible to the specified parts of the website (for example, the guest could not access the options)
b) do support for OSPy and plugins for Python 3. I've already started, but got stuck on the first error listing.

Please look in my branch on github and if you have raspberry pi try out what the system can do.
I am willing to pay you your time (pay-pal, card ...) I know that this device has great potential and is used by several users around the world for their needs.
![Snímek obrazovky (70)](https://user-images.githubusercontent.com/7847139/98483759-4c98d080-220b-11eb-9d13-0566fbcd085e.jpg)
![Snímek obrazovky (71)](https://user-images.githubusercontent.com/7847139/98483761-4dc9fd80-220b-11eb-8520-ace880b8848e.jpg)
![Snímek obrazovky (72)](https://user-images.githubusercontent.com/7847139/98483763-4dc9fd80-220b-11eb-9339-bbdf95bcc4c6.jpg)
![Snímek obrazovky (73)](https://user-images.githubusercontent.com/7847139/98483764-4e629400-220b-11eb-9fd3-335eddb3fdef.jpg)
![Snímek obrazovky (74)](https://user-images.githubusercontent.com/7847139/98483765-4e629400-220b-11eb-8570-f6b4f621127c.jpg)
![Snímek obrazovky (75)](https://user-images.githubusercontent.com/7847139/98483767-4efb2a80-220b-11eb-804d-8fb73ebcf017.jpg)
![Snímek obrazovky (76)](https://user-images.githubusercontent.com/7847139/98483768-4f93c100-220b-11eb-9c48-a028dee4b84c.jpg)
![Snímek obrazovky (77)](https://user-images.githubusercontent.com/7847139/98483769-4f93c100-220b-11eb-9cd5-497345caa152.jpg)
![Snímek obrazovky (78)](https://user-images.githubusercontent.com/7847139/98483771-50c4ee00-220b-11eb-8304-e26d06239bdd.jpg)
![Snímek obrazovky (80)](https://user-images.githubusercontent.com/7847139/98483773-515d8480-220b-11eb-95ea-1a1b3e1b94b2.jpg)
![Snímek obrazovky (81)](https://user-images.githubusercontent.com/7847139/98483774-528eb180-220b-11eb-8547-38c1986c30b1.jpg)
![Snímek obrazovky (82)](https://user-images.githubusercontent.com/7847139/98483775-528eb180-220b-11eb-8252-0798f495861b.jpg)
![Snímek obrazovky (83)](https://user-images.githubusercontent.com/7847139/98483776-53274800-220b-11eb-92ff-ff16c26c281b.jpg)
![Snímek obrazovky (84)](https://user-images.githubusercontent.com/7847139/98483777-53274800-220b-11eb-9b5a-f31858084b17.jpg)
![Snímek obrazovky (85)](https://user-images.githubusercontent.com/7847139/98483779-53bfde80-220b-11eb-8763-a4a75d8888a8.jpg)
![Snímek obrazovky (86)](https://user-images.githubusercontent.com/7847139/98483781-53bfde80-220b-11eb-86ab-ba15875ebfbf.jpg)

**Thank you very much Martin Pihrt
www.pihrt.com Czech Republic**

**Comment by bkoblenz** [comment]
Don’t think I am too interested in this. 

I expect changing to python 3 is a big effort. 

For your permissions here is my advice:
1) look at the login code and pay attention to where the “user” is stored 
2) on the relevant pages, check to make sure the user (likely web.config._session[‘user’]) has the appropriate privileges and if not, raise web.forbidden()

**Comment by martinpihrt** [comment]
OK thank you for answer
Regards Martin Pihrt
